spring:
  main:
    allow-circular-references: true
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jobdev
    username: root
    password: 132567
server:
  port: 8080